// Chmod Generator Constants

export const SET_CHECKED = 'SET_CHECKED';
export const SET_NUMBER_FIELD_VALUE = 'SET_NUMBER_FIELD_VALUE';
export const SET_TEXT_FIELD_VALUE = 'SET_TEXT_FIELD_VALUE';

// Crontab Generator Constants

// days constants
export const SET_DAYS_RADIO_BUTTON_VALUE='SET_DAYS_RADIO_BUTTON_VALUE';
export const SET_DAYS_OPTION_VALUE='SET_DAYS_OPTION_VALUE'
export const SET_DAY_HAS_ERROR='SET_DAY_HAS_ERROR'

// hours constants

export const SET_HOURS_RADIO_BUTTON_VALUE='SET_HOURS_RADIO_BUTTON_VALUE';
export const SET_HOURS_OPTION_VALUE='SET_HOURS_OPTION_VALUE'
export const SET_HOUR_HAS_ERROR='SET_HOUR_HAS_ERROR'

// minutes constants

export const SET_MINUTES_RADIO_BUTTON_VALUE='SET_MINUTES_RADIO_BUTTON_VALUE';
export const SET_MINUTES_OPTION_VALUE='SET_MINUTES_OPTION_VALUE'
export const SET_MINUTE_HAS_ERROR='SET_MINUTE_HAS_ERROR'

// month constants

export const SET_MONTHS_RADIO_BUTTON_VALUE='SET_MONTHS_RADIO_BUTTON_VALUE';
export const SET_MONTHS_OPTION_VALUE='SET_MONTHS_OPTION_VALUE'
export const SET_MONTH_HAS_ERROR='SET_MONTH_HAS_ERROR'

// weekdays constants

export const SET_WEEKDAYS_RADIO_BUTTON_VALUE='SET_WEEKDAYS_RADIO_BUTTON_VALUE';
export const SET_WEEKDAYS_OPTION_VALUE='SET_WEEKDAYS_OPTION_VALUE'
export const SET_WEEKDAY_HAS_ERROR='SET_WEEKDAY_HAS_ERROR'

// user path/command constants

export const SET_COMMAND_TO_EXECUTE='SET_COMMAND_TO_EXECUTE'
export const SET_COMMAND_HAS_ERROR='SET_COMMAND_HAS_ERROR'

// generate crontab line

export const GENERATE_CRONTAB_LINE='GENERATE_CRONTAB_LINE'

// crontab output

export const HOW_TO_HANDLE_OUTPUT='HOW_TO_HANDLE_OUTPUT'
export const SET_PATH_TO_FILE_VALUE='SET_PATH_TO_FILE_VALUE'
export const SET_EMAIL_VALUE='SET_EMAIL_VALUE'